stages:
  - build_and_test
  - deploy

services:
  - docker:dind

build_and_test_app:
  stage: build_and_test
  image: docker:latest
  script:
    - docker build -t pytfastapimodels .
    - docker run --rm pytfastapimodels pytest -s -v

deploy_app:
  stage: deploy
  image: docker:latest
  script:
    - docker compose up -d --build --force-recreate
  only:
    - master