stages:
  - build
  - test
  - deploy

build_app:
  stage: build
  script:
    - docker build -t pytfastapimodels

run_tests:
  stage: test
  image: $CI_REGISTRY_IMAGE:latest
  script:
    - docker run --rm pytfastapimodels pytest -s -v

deploy_app:
  stage: deploy
  script:
    - docker compose up -d
  only:
    - master